trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  # Predefined Azure Pipelines variables. There's no need to modify them.
  JF_GIT_PROJECT: $(System.TeamProject)
  JF_GIT_REPO: $(Build.Repository.Name)
  JF_GIT_API_ENDPOINT: $(System.CollectionUri)
  JF_GIT_BASE_BRANCH: $(Build.SourceBranchName)
  JF_GIT_OWNER: $(System.TeamProject)
  JF_GIT_PROVIDER: 'azureRepos'
  
jobs:
- deployment: MVN_PIPELINE
  displayName: End to End MVN pipeline
  environment: 
    name: gcp
    resourceType: virtualMachine
    resourceName: ip-172-18-96-159
  strategy:
    runOnce:
      deploy:   
          steps:
            - checkout: self
            - task: JfrogCliV2@1
              name: jf_setup # This name is crucial for the next step
              inputs:
                jfrogPlatformConnection: 'azure-jfrog-platform-oidc'
                command: |
                  jf c show
                  jf rt ping
                  jf rt curl "/api/repositories?type=virtual"

            - task: Bash@3
              displayName: 'Run Frogbot Scan'
              env:
                # Syntax: $(taskName.variableName)
                JF_ACCESS_TOKEN: $(jf_setup.oidc_token)
                JF_URL: "https://psazuse.jfrog.io"
                
                JF_GIT_TOKEN: $(JF_GIT_TOKEN)
                #JF_WORKING_DIR: src
                JF_PATH_EXCLUSIONS: "*.git*;*node_modules*"
                JF_INCLUDE_ALL_VULNERABILITIES: "TRUE"
                JF_FAIL: "FALSE"
                JF_GIT_AGGREGATE_FIXES: "FALSE"
                JF_FIXABLE_ONLY: "TRUE"
                JF_MIN_SEVERITY: "Medium"
                JF_AVOID_EXTRA_MESSAGES: "TRUE"
                JF_PR_COMMENT_TITLE: ""
              inputs:
                targetType: 'inline'
                script: |
                  # Verification (optional)
                  echo "Target Artifactory: $JF_URL"
                  
                  # Download & Run Frogbot
                  curl -fLg "https://releases.jfrog.io/artifactory/frogbot/v2/2.29.4/getFrogbot.sh" | sh
                  ./frogbot cfpr