trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  # Predefined Azure Pipelines variables. There's no need to modify them.
  JF_GIT_PROJECT: $(System.TeamProject)
  JF_GIT_REPO: $(Build.Repository.Name)
  JF_GIT_API_ENDPOINT: $(System.CollectionUri)
  JF_GIT_BASE_BRANCH: $(Build.SourceBranchName)
  JF_GIT_OWNER: $(System.TeamProject)
  JF_GIT_PROVIDER: 'azureRepos'
  
jobs:
- deployment: MVN_PIPELINE
  displayName: End to End MVN pipeline
  environment: 
    name: gcp
    resourceType: virtualMachine
    resourceName: ip-172-18-96-159
  strategy:
    runOnce:
      deploy:   
          steps:
            - checkout: self
            - task: JfrogCliV2@1
              inputs:
                jfrogPlatformConnection: 'azure-jfrog-platform-oidc'
                command: |
                  jf c show
                  jf rt ping
                  jf rt curl "/api/repositories?type=virtual"
            - task: CmdLine@2
              displayName: 'Download and Run Frogbot'
              env:
                  JF_URL: "https://psemea.jfrog.io"
                  #JF_ACCESS_TOKEN: $(JF_ACCESS_TOKEN)
                  JF_GIT_TOKEN: $(JF_GIT_TOKEN)
                  #JF_WORKING_DIR: src
                  JF_PATH_EXCLUSIONS: "*.git*;*node_modules*"
                  JF_INCLUDE_ALL_VULNERABILITIES: "TRUE"
                  JF_FAIL: "FALSE"
                  JF_GIT_AGGREGATE_FIXES: "FALSE"
                  JF_FIXABLE_ONLY: "TRUE"
                  JF_MIN_SEVERITY: "Medium"
                  JF_AVOID_EXTRA_MESSAGES: "TRUE"
                  JF_PR_COMMENT_TITLE: ""
      
              inputs:
                jfrogPlatformConnection: 'azure-jfrog-platform-oidc'
                script: |
                  getFrogbotScriptPath=$(if [ -z "$JF_RELEASES_REPO" ]; then echo "https://releases.jfrog.io"; else echo "${JF_URL}/artifactory/${JF_RELEASES_REPO}"; fi)
                  curl -fLg "$getFrogbotScriptPath/artifactory/frogbot/v2/2.29.4/getFrogbot.sh" | sh
                  ./frogbot cfpr