name: "Artifactory upload download"
description: "This action upload and download from artifactory"
inputs:
  sourcefile:
    description: "source file path"
    required: true
  destinationfile:
    description: "Destination file path"
    required: false
    default: "."
  action:
    description: "Action upload/download/delete/check"
    required: true
    default: "upload"
  artifactory_url:
    description: "artifactory url"
    required: true
  additional_flags:
    description: "additional flag to pass along with the command"
    required: false
outputs:
  search_exists:
    description: "Indicates if the source file exists in Artifactory"
    value: ${{ steps.artifactory-linux.outputs.exists || steps.artifactory-win.outputs.exists || false }}
  download_status:
    description: "Status of the download operation"
    value: ${{ steps.artifactory-linux.outputs.download_status || steps.artifactory-win.outputs.download_status || 0 }}
  upload_status:
    description: "Status of the upload operation"
    value: ${{ steps.artifactory-linux.outputs.upload_status || steps.artifactory-win.outputs.upload_status || 0 }}
  delete_status:
    description: "Status of the delete operation"
    value: ${{ steps.artifactory-linux.outputs.delete_status || steps.artifactory-win.outputs.delete_status || 0 }}

runs:
  using: "composite"
  steps:
    - uses: jfrog/setup-jfrog-cli@v4
      with:
        oidc-provider-name: "anilkt-github"
        oidc-audience: "anilkt-jfrog-oidc"
      env:
        JF_URL: ${{ inputs.artifactory_url }}

    - name: Linux Artifactory Action
      if: runner.os != 'Windows'
      shell: bash
      id: artifactory-linux
      run: |
        if [ "${{ inputs.action }}" == "upload" ]; then
          jf rt u "${{ inputs.sourcefile }}" "${{ inputs.destinationfile }}" ${{ inputs.additional_flags }}
          upload_status=$?
          if [ "$upload_status" -eq 0 ]; then
            echo "upload_status=$upload_status" >> $GITHUB_OUTPUT
            echo "upload is successful"
          else
            echo "upload_status=$upload_status" >> $GITHUB_OUTPUT
            echo "upload failed"
          fi
        elif [ "${{ inputs.action }}" == "download" ] ; then
          jf rt dl "${{ inputs.sourcefile }}" "${{ inputs.destinationfile }}" ${{ inputs.additional_flags }}
          download_status=$?
          if [ "$download_status" -eq 0 ]; then
            echo "download_status=$download_status" >> $GITHUB_OUTPUT
            echo "Download is successful"
          else
            echo "download_status=$download_status" >> $GITHUB_OUTPUT
            echo "Download failed"
          fi
        elif [ "${{ inputs.action }}" == "delete" ] ; then
           jf rt del "${{ inputs.sourcefile }}" ${{ inputs.additional_flags }}
           delete_status=$?
            if [ "$delete_status" -eq 0 ]; then
              echo "delete_status=$delete_status" >> $GITHUB_OUTPUT
              echo "delete is successful"
            else
              echo "delete_status=$delete_status" >> $GITHUB_OUTPUT
              echo "delete failed"
            fi
        elif [ "${{ inputs.action }}" == "check" ] ; then
          search_exists=$(jf rt s "${{ inputs.sourcefile }}" --count ${{ inputs.additional_flags }})
          echo $search_exists
          if [ "$search_exists" -gt "0" ] ; then
            echo "search_exists=$search_exists" >> $GITHUB_OUTPUT
            echo "found source"
          else
            echo "search_exists=$search_exists" >> $GITHUB_OUTPUT
            echo "didn't find source"
          fi
        fi

    - name: Windows Artifactory Action
      if: runner.os == 'Windows'
      shell: powershell
      id: artifactory-win
      run: |
        if ("${{ inputs.action }}" -eq "upload") {
          jf rt u "${{ inputs.sourcefile }}" "${{ inputs.destinationfile }}" ${{ inputs.additional_flags }})
          upload_status=$LASTEXITCODE
          if ($upload_status -gt 0) {
            echo "upload_status=$upload_status" >> $env:GITHUB_OUTPUT
            echo "upload is successful"
          } else {
            echo "upload_status=$upload_status" >> $env:GITHUB_OUTPUT
            echo "upload failed"
          }
        } elseif ("${{ inputs.action }}" -eq "download") {
          jf rt dl "${{ inputs.sourcefile }}" "${{ inputs.destinationfile }}" ${{ inputs.additional_flags }}
          download_status=$LASTEXITCODE
          if ($download_status -gt 0) {
            echo "download_status=$download_status" >> $env:GITHUB_OUTPUT
            echo "download is successful"
          } else {
            echo "download_status=$download_status" >> $env:GITHUB_OUTPUT
            echo "download failed"
          }
        } elseif ("${{ inputs.action }}" -eq "delete") {
          jf rt del "${{ inputs.sourcefile }}" ${{ inputs.additional_flags }}
          delete_status=$LASTEXITCODE
          if ($delete_status -gt 0) {
            echo "delete_status=$delete_status" >> $env:GITHUB_OUTPUT
            echo "delete is successful"
          } else {
            echo "delete_status=$delete_status" >> $env:GITHUB_OUTPUT
            echo "delete failed"
          }
        } elseif ("${{ inputs.action }}" -eq "check") {
          $search_exists=$(jf rt s "${{ inputs.sourcefile }}" --count ${{ inputs.additional_flags }})
          echo $search_exists
          if ($search_exists -gt 0) {
            echo "search_exists=true" >> $env:GITHUB_OUTPUT
            echo "found source"
          } else {
            echo "search_exists=false" >> $env:GITHUB_OUTPUT
            echo "didn't find source"
          }
        }
