name: "JFrog-GitHub NPM Publish OIDC Integration"
on: workflow_dispatch


# This is required as per below link
# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#adding-permissions-settings
permissions:
  contents: read # Allow reading repository content
  packages: write # Allow writing to GitHub Packages
  id-token: write # Required for OIDC authentication with JFrog

jobs:
  build:
     #runs-on: ubuntu-latest
     runs-on: self-hosted
     defaults:
      run:
        working-directory: ./package
     steps:
       - name: Checkout
         uses: actions/checkout@v3
              
       - name: Setup Node npm
         uses: actions/setup-node@v3
   
       - name: Setup JFrog CLI
         uses: jfrog/setup-jfrog-cli@v4
         env:  
           JF_URL: ${{ vars.JF_URL }}
           JF_USER: ${{ vars.JF_USER }}
           JF_ACCESS_TOKEN: ${{ vars.JF_ACCESS_TOKEN }}                    
           
       - name: Run Audit scan for the git workspace
         run: jf audit .

       - name: Set CLI Config
         run: jf npm-config --global=true --repo-resolve=${{ vars.PLATFORM_REPO }} --repo-deploy=${{ vars.PLATFORM_REPO }} --project=${{ vars.JFROG_PROJECT_KEY }}

           
       - name: Install Dependencies
         run: jf npm install --build-name=${{ vars.BUILD_NAME }} --build-number=${{ github.run_number }} --project=${{ vars.JFROG_PROJECT_KEY }}
           
       - name: Run tests
         run: npm test
         
       - name: Publish
         run: jf npm publish --build-name=${{ vars.BUILD_NAME }} --build-number=${{ github.run_number }} --project=${{ vars.JFROG_PROJECT_KEY }}
         
       - name: Publish Build info With JFrog CLI
         run: |
          # Collect environment variables for the build
          jf rt build-collect-env ${{ vars.BUILD_NAME }} ${{ github.run_number }} --project=${{ vars.JFROG_PROJECT_KEY }}
          
          # Collect VCS details from git and add them to the build 
          jf rt build-add-git ${{ vars.BUILD_NAME }} ${{ github.run_number }} --project=${{ vars.JFROG_PROJECT_KEY }}
          jf rt build-add-dependencies ${{ vars.BUILD_NAME }} ${{ github.run_number }} --project=${{ vars.JFROG_PROJECT_KEY }}
          
          # Publish build info 
          jf rt build-publish ${{ vars.BUILD_NAME }} ${{ github.run_number }} --project=${{ vars.JFROG_PROJECT_KEY }}

          

       - name: Run build scan
         run: jf rt build-scan naresh-npm-xray ${{ github.run_number }}
